### ISSUE TITLE
cannot find module 'ngraph.centrality'

### ISSUE THREAD

**Issue by haukehess** [bilthon/ln-centrality#1]
I'm new to node.js, so please be gentle with my noob-errors:

Cloned ln-centrality to my myNode into /home/admin
Copied graph.json into /home/admin/ln-centrality/src/assets

then (from /home/admin and /home/admin/ln-centrality as current dir):

$ node . -t <publickey of myNode>

error:

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'ngraph.centrality'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/admin/ln-centrality/src/index.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)

**Comment by bilthon** [comment]
Oh well, that's because you need to install dependencies firts. Just type `npm install` and then run the script. I will add this to the README instructions.

You might also want to specify a target node for the simulation part. You do this by providing a node's public key after the `-t` cli argument.

**Comment by haukehess** [comment]
Thanks, that did the trick.
